language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_install:
  - chmod +x mvnw

install: mvn install -DskipTests

notifications:
  email:
    on_success: never

sudo: false